### ISSUE TITLE
SoundManager.Instance.Volumeとhandle.volumeの違いについて

### ISSUE THREAD

**Issue by TakashiHamada** [wakepon/SoundManager#1]
https://github.com/wakepon/SoundManager/blob/31d40afebce306a030b4a98781d13f3f09e60618/Assets/Demo/Demo.cs#L14

以下ようにハンドルを利用する場合と、そうでない場合で、どちらもボリュームの調整ができますが、使い分け等あれば教えて頂けないでしょうか？

```
var handle = this.PlaySe("seTest");
SoundManager.Instance.Volume.se = 0f; // <= 0
handle.volume = 0f; // <= 1
```

SEの場合、ハンドルを使用した場合は特定のSEの音量を調節でき、そうでない場合（SoundManager.Instance.Volume）はすべてのSEの音量を対象にするという認識で合っていますでしょうか？

どうぞよろしくおねがいします。

**Comment by wakepon** [comment]
その認識であっています。
SoundManager.Instance.Volumeはマスターボリュームです。
アプリ上で、ボリューム調整UIを作ったりするときは、こちらを使ってください。
Handleのボリュームはそれぞれの音のボリュームを変えます。

**Comment by TakashiHamada** [comment]
承知しました。ご回答ありがとうございます。クローズします。
