### ISSUE TITLE
簡易版の制限について

### ISSUE THREAD

**Issue by TakashiHamada** [wakepon/SoundManager#2]
https://github.com/wakepon/SoundManager/blob/31d40afebce306a030b4a98781d13f3f09e60618/Assets/Demo/Demo.cs#L26

```SoundManager.Instance.PlaySe("key")```を利用した場合と、
簡易版の```this.PlaySe("key")```を利用した場合で、簡易版に機能の制限はあるのでしょうか？

基本的に、簡易版を使用するのが推奨なのでしょうか？

**Comment by wakepon** [comment]
どちらを使っても良いですが簡易版の方はMonobehaviourからのみ使えます。
あとは、遅延実行バージョンの方はHandleが返ってこないのでちょっと不便です。
しかし、先程遅延実行バージョンもHandleを返すようにしたので、基本は簡易版を使うので良いと思います。

**Comment by TakashiHamada** [comment]
ご回答、追加の実装ありがとうござます。クローズします。
